language: python
python:
  - "2.7"
  - "3.6"
env:
  - BML_TESTS="05"
  - BML_TESTS="35"
  - BML_TESTS="01 02 03 04 06 07 08 09 10 11 12 33 36"
  - BML_TESTS="13 14 15 16 17 18 19 20 21 22 24 25 26 27 28 29 30 31 32 34"
  - BML_TESTS="23 37"
install:
  - pip install numpy
  - pip install scipy
  - pip install pystemmer
  - python setup.py develop
script:
  - export TESTS=$(for t in $BML_TESTS; do ls bigml/tests/*$t*;done|paste -sd ",")
  - echo $TESTS
  - python setup.py nosetests --nocapture --tests=$TESTS
